### ISSUE TITLE
Update for BEAST2.7?

### ISSUE THREAD

**Issue by sebastianduchene** [kche309/beast-developer-guide#1]
This guide is very useful. Thanks for putting it together! 
Is there any chance you would update it for BEAST2.7?

**Comment by kche309** [comment]
Hi @sebastianduchene, we are planning to add an updated development guide for BEAST 2.7 in the future. 

In the meantime, there are two guides available (mainly setup focused) for BEAST 2.7:  
https://github.com/CompEvol/BeastFX/blob/master/README.md
https://github.com/CompEvol/BeastFX/blob/master/DevGuideIntelliJ.md

**Comment by sebastianduchene** [comment]
That is super helpful. Thanks, @kche309 !
